<a href="https://colab.research.google.com/github/Avichay3/Full-training/blob/numpy-pandas-training/Copy_of_Pandas_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas puzzles

Enjoy the puzzles!

## Importing pandas

### Getting started and checking your pandas setup

Difficulty: *easy*

**1.** Import pandas under the name `pd`.

In [1]:
import pandas as pd

**2.** Print the version of pandas that has been imported.

In [2]:
pd.__version__

'2.2.2'

**3.** Print out all the version information of the libraries that are required by the pandas library.

In [3]:
pd.show_versions()

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.12.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 6.6.105+
Version               : #1 SMP Thu Oct  2 10:42:05 UTC 2025
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : en_US.UTF-8
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.2
numpy                 : 2.0.2
pytz                  : 2025.2
dateutil              : 2.9.0.post0
setuptools            : 75.2.0
pip                   : 24.1.2
Cython                : 3.0.12
pytest                : 8.4.2
hypothesis            : None
sphinx                : 8.2.3
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 5.4.0
html5lib              : 1.1
pymysql               : None
psycopg2              : 2.9.11
jinja2                : 3.1.6
IPython               : 7.34.0
pandas_datareader     : 0.10.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.13.5
bottleneck            : 1.4.2
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2025.3.0
gcsfs                 : 2025.3.0
matplotlib            : 3.10.0
numba                 : 0.60.0
numexpr               : 2.14.1
odfpy                 : None
openpyxl              : 3.1.5
pandas_gbq            : 0.29.2
pyarrow               : 18.1.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.16.3
sqlalchemy            : 2.0.44
tables                : 3.10.2
tabulate              : 0.9.0
xarray                : 2025.10.1
xlrd                  : 2.0.2
zstandard             : 0.25.0
tzdata                : 2025.2
qtpy                  : None
pyqt5                 : None

## DataFrame basics

### A few of the fundamental routines for selecting, sorting, adding and aggregating data in DataFrames

Difficulty: *easy*

Note: remember to import numpy using:
```python
import numpy as np
```

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
(This is just some meaningless data I made up with the theme of animals and trips to a vet.)

**4.** Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

In [4]:
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data,index = labels)
print(df.head())

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no

**5.** Display a summary of the basic information about this DataFrame and its data.

In [5]:
df.describe()

            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

**6.** Return the first 3 rows of the DataFrame `df`.

In [6]:
df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

**7.** Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [7]:
df['animal']
df['age']

a    2.5
b    3.0
c    0.5
d    NaN
e    5.0
f    2.0
g    4.5
h    NaN
i    7.0
j    3.0
Name: age, dtype: float64

**8.** Select the data in rows `[3, 4, 8]` *and* in columns `['animal', 'age']`.

In [8]:
df.iloc[[3, 4, 8] , [0, 1]]

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

**9.** Select only the rows where the number of visits is greater than 3.

In [9]:
df.loc[df['visits'] > 3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

**10.** Select the rows where the age is missing, i.e. is `NaN`.

In [10]:
df[df['age'].isna()]

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

**11.** Select the rows where the animal is a cat *and* the age is less than 3.

In [11]:
df[(df['animal'] == 'cat') & (df['age'] < 3)]

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

**12.** Select the rows the age is between 2 and 4 (inclusive).

In [12]:
df[(df['age'] >= 2) & (df['age'] <= 4) ]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

**13.** Change the age in row 'f' to 1.5.

In [13]:
df.loc['f', 'age'] = 1.5

**14.** Calculate the sum of all visits (the total number of visits).

In [14]:
print(df['visits'].sum())

19

**15.** Calculate the mean age for each different animal in `df`.

In [15]:
print(df.groupby('animal')['age'].mean())

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

**16.** Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [16]:
df.loc['k'] = [5.5, 'dog', 'no', 2]
df = df.drop('k')

**17.** Count the number of each type of animal in `df`.

In [17]:
df['animal'].value_counts()

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

**18.** Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visit' column in *ascending* order.

In [18]:
df['age'].sort_values(ascending=False)
df['visits'].sort_values(ascending=True)

a    1
g    1
h    1
j    1
c    2
e    2
i    2
b    3
d    3
f    3
Name: visits, dtype: object

**19.** The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.

In [19]:
df.loc[df['priority'] == 'yes', 'priority'] = True
df.loc[df['priority'] == 'no', 'priority'] = False
df['priority']

a     True
b     True
c    False
d     True
e    False
f    False
g    False
h     True
i    False
j    False
Name: priority, dtype: object

**20.** In the 'animal' column, change the 'snake' entries to 'python'.

In [20]:
df.loc[df['animal'] == 'snake', 'animal'] = 'python'
df['animal']

a       cat
b       cat
c    python
d       dog
e       dog
f       cat
g    python
h       cat
i       dog
j       dog
Name: animal, dtype: object

**21.** For each animal type and each number of visits, find the mean age. In other words, each row is an animal, each column is a number of visits and the values are the mean ages (hint: use a pivot table).

In [21]:
df.groupby(['animal', 'visits'])['age'].mean()

animal  visits
cat     1          2.5
        3         2.25
dog     1          3.0
        2          6.0
        3          NaN
python  1          4.5
        2          0.5
Name: age, dtype: object

## DataFrames: using complicated functions

Difficulty: *medium*

here you will be asked to generate your own test data and manipulate it using functions you will have to create.

**22.** Create a dataframe with 1000 rows and 3 columns. The columns are to be the following:
        - age: an integer, uniformly distributed between 20 to 65
        - skill: a float, normally distributed between 0 and 1, with expected value = 0.5 and standard deviation = 0.3
        - height: a float with 2 digits after the decimal point, between 1.5 to 2.0
you might want to use numpy.random

In [22]:
import numpy as np
import pandas as pd

age = np.random.randint(20, 66, size=1000)
skill = np.random.normal(0.5, 0.3, size=1000)
skill = np.clip(skill, 0, 1)
height = np.round(np.random.uniform(1.5, 2.0, size=1000), 2)
df = pd.DataFrame({'age': age, 'skill': skill, 'height': height})
df.head(5)

   age     skill  height
0   20  0.456513    1.90
1   52  0.924575    1.67
2   28  0.442854    1.85
3   38  0.822990    1.77
4   49  0.706352    1.74

**23.** Add the dataframe a new columns, called salary, when:
        salary = 1000*((age^2)/1000 + 1.7*skill + 0.4*exp(-(height-1.7)**2)

In [23]:
df.loc[:, 'salary'] = 1000*((df['age']**2)/1000 + 1.7*df['skill'] + 0.4*np.exp(-(df['height']-1.7)**2))
df.head(5)

   age     skill  height       salary
0   20  0.456513    1.90  1560.388173
1   52  0.924575    1.67  4675.417013
2   28  0.442854    1.85  1927.952916
3   38  0.822990    1.77  3241.127210
4   49  0.706352    1.74  4001.159129

**24.** Split the dataframe to groups by the age left digit and by the age. for each group compute:
        - the number of rows
        - the mean salary
        - the maximum height

In [24]:
df['age_left_digit'] = df['age'] // 10
df.groupby('age_left_digit').agg({'age': 'count', 'salary': 'mean', 'height': 'max'})

                age       salary  height
age_left_digit
2               212  1862.368736    1.99
3               211  2452.760360    2.00
4               223  3219.136073    2.00
5               207  4167.102451    2.00
6               147  5157.235367    2.00

**25.** Now split the dataframe to groups by age. for each group compute the mean salary, split by the sum of heights.

In [25]:
grouped = df.groupby('age').agg(
    mean_salary=('salary', 'mean'),
    sum_height=('height', 'sum')
)

grouped['mean_salary_div_sum_height'] = grouped['mean_salary'] / grouped['sum_height']

print(grouped.head(10))

     mean_salary  sum_height  mean_salary_div_sum_height
age
20   1634.579539       41.84                   39.067389
21   1698.397398       32.37                   52.468254
22   1888.759627       35.89                   52.626348
23   1595.261916       31.33                   50.918031
24   1736.170054       40.28                   43.102534
25   1954.598775       38.01                   51.423277
26   2071.673391       22.48                   92.156290
27   2063.771021       43.73                   47.193483
28   2066.073562       42.30                   48.843347
29   1899.898498       42.30                   44.914858

**26.** Add these lines to your code:

        import matplotlib.pyplot as plt
        %matplotlib inline
        
Now try using the pd.DataFrame.plot function to show your data. Try also using pd.DataFrame.boxplot.

In [26]:
import matplotlib.pyplot as plt
%matplotlib inline

**27.** Save the result as a csv, then read the csv to the variable "data" using pandas

In [27]:
df = pd.DataFrame({'age': age, 'skill': skill, 'height': height})
df.to_csv('data.csv', index=False)
data = pd.read_csv('data.csv')
data.head()

   age     skill  height
0   20  0.456513    1.90
1   52  0.924575    1.67
2   28  0.442854    1.85
3   38  0.822990    1.77
4   49  0.706352    1.74

## DataFrames: beyond the basics

### Slightly trickier: you may need to combine two or more methods to get the right answer

Difficulty: *medium*

The previous section was tour through some basic but essential DataFrame operations. Below are some ways that you might need to cut your data, but for which there is no single "out of the box" method.

**28.** You have a DataFrame `df` with a column 'A' of integers. For example:
```python
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
```

How do you filter out rows which contain the same integer as the row immediately above?

In [28]:
import pandas as pd

df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
df['diff'] = df['A'].diff()

filtered_df = df[df['A'].diff() != 0]
print(filtered_df)

   A  diff
0  1   NaN
1  2   1.0
3  3   1.0
4  4   1.0
5  5   1.0
8  6   1.0
9  7   1.0

**29.** Given a DataFrame of numeric values, say
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # a 5x3 frame of float values
```

how do you subtract the row mean from each element in the row?

In [29]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.random(size=(5, 3)))
print("Original DataFrame:")
print(df, '\n')

df_sub = df.sub(df.mean(axis=1), axis=0)
print("After subtracting row mean:")
print(df_sub)

Original DataFrame:
          0         1         2
0  0.596490  0.560483  0.233620
1  0.767504  0.914297  0.279959
2  0.334652  0.294587  0.898723
3  0.659901  0.357738  0.274952
4  0.938283  0.007737  0.635021

After subtracting row mean:
          0         1         2
0  0.132959  0.096952 -0.229911
1  0.113584  0.260377 -0.373961
2 -0.174669 -0.214734  0.389403
3  0.229037 -0.073126 -0.155912
4  0.411269 -0.519277  0.108008

**30.** Suppose you have DataFrame with 10 columns of real numbers, for example:

```python
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
```
Which column of numbers has the smallest sum? (Find that column's label.)

In [30]:
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
print(df)
col_with_min_sum = df.sum().idxmin()
print(col_with_min_sum)

          a         b         c         d         e         f         g  \
0  0.598839  0.178578  0.473788  0.446136  0.832727  0.390052  0.487266
1  0.014451  0.473468  0.978112  0.069807  0.054095  0.855872  0.354064
2  0.941186  0.490456  0.549617  0.018991  0.305573  0.076364  0.913466
3  0.868133  0.132938  0.478224  0.510449  0.788813  0.006771  0.925118
4  0.558112  0.712263  0.153395  0.390053  0.551596  0.042193  0.235124

          h         i         j
0  0.112625  0.129214  0.986898
1  0.139804  0.351405  0.373386
2  0.206017  0.010682  0.060821
3  0.823312  0.410057  0.331830
4  0.260662  0.587316  0.734096
f

**31.** How do you count how many unique rows a DataFrame has (i.e. ignore all rows that are duplicates)?

In [31]:
import pandas as pd

df = pd.DataFrame({
    'A': [1, 2, 2, 3, 3, 3],
    'B': [4, 5, 5, 6, 6, 6]
})

print(df)

num_unique_rows = len(df.drop_duplicates())
print(num_unique_rows)

   A  B
0  1  4
1  2  5
2  2  5
3  3  6
4  3  6
5  3  6
3

The next three puzzles are slightly harder...

**32.** You have a DataFrame that consists of 10 columns of floating--point numbers. Suppose that exactly 5 entries in each row are NaN values. For each row of the DataFrame, find the *column* which contains the *third* NaN value.

(You should return a Series of column labels.)

In [32]:
import pandas as pd
import numpy as np

np.random.seed(0)
df = pd.DataFrame(np.random.randn(5, 10), columns=list('abcdefghij'))


for i in range(len(df)):
    nan_cols = np.random.choice(df.columns, 5, replace=False)
    df.loc[i, nan_cols] = np.nan


third_nan_col = df.isna().cumsum(axis=1).eq(3).idxmax(axis=1)

print(df)
print("\nThird NaN column per row:")
print(third_nan_col)

          a         b         c         d         e         f   g         h  \
0  1.764052  0.400157       NaN       NaN       NaN -0.977278 NaN -0.151357
1  0.144044  1.454274  0.761038       NaN  0.443863  0.333674 NaN       NaN
2 -2.552990  0.653619  0.864436       NaN       NaN -1.454366 NaN -0.187184
3       NaN  0.378163 -0.887786 -1.980796       NaN       NaN NaN  1.202380
4       NaN -1.420018 -1.706270  1.950775 -0.509652       NaN NaN       NaN

          i        j
0 -0.103219      NaN
1       NaN      NaN
2       NaN      NaN
3 -0.387327      NaN
4       NaN -0.21274

Third NaN column per row:
0    e
1    h
2    g
3    f
4    g
dtype: object

**33.** A DataFrame has a column of groups 'grps' and and column of numbers 'vals'. For example:

```python
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
```
For each *group*, find the sum of the three greatest values.

In [33]:
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})

result = (
    df.groupby('grps')['vals']
      .apply(lambda x: x.nlargest(3).sum())
      .reset_index(name='sum_top3')
)

print(result)

  grps  sum_top3
0    a       409
1    b       156
2    c       345

**34.** A DataFrame has two integer columns 'A' and 'B'. The values in 'A' are between 1 and 100 (inclusive). For each group of 10 consecutive integers in 'A' (i.e. `(0, 10]`, `(10, 20]`, ...), calculate the sum of the corresponding values in column 'B'.

In [34]:
df = pd.DataFrame({'A': np.random.randint(1, 101, 20),
                   'B': np.random.randint(1, 101, 20)})
sum = df.groupby(pd.cut(df['A'], bins=range(0, 101, 10))).agg({'B': 'sum'})
print(sum)

             B
A
(0, 10]    155
(10, 20]    71
(20, 30]    12
(30, 40]   231
(40, 50]   229
(50, 60]   161
(60, 70]    97
(70, 80]     5
(80, 90]   115
(90, 100]    0

/tmp/ipython-input-18961060.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sum = df.groupby(pd.cut(df['A'], bins=range(0, 101, 10))).agg({'B': 'sum'})

## DataFrames: harder problems

### These might require a bit of thinking outside the box...

...but all are solvable using just the usual pandas/NumPy methods (and so avoid using explicit `for` loops).

Difficulty: *hard*

**35.** Consider a DataFrame `df` where there is an integer column 'X':
```python
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
```
For each value, count the difference back to the previous zero (or the start of the Series, whichever is closer). These values should therefore be `[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]`. Make this a new column 'Y'.

In [35]:
import pandas as pd

df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})

count = 0
Y = []

for val in df['X']:
    if val == 0:
        count = 0
    else:
        count += 1
    Y.append(count)

df['Y'] = Y
print(df)

   X  Y
0  7  1
1  2  2
2  0  0
3  3  1
4  4  2
5  2  3
6  5  4
7  0  0
8  3  1
9  4  2

**36.** Consider a DataFrame containing rows and columns of purely numerical data. Create a list of the row-column index locations of the 3 largest values.

In [36]:
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randint(0, 100, (4, 4)), columns=list('ABCD'))
top3 = df.unstack().nlargest(3)
locations = [(row, col) for col, row in top3.index]

print(df)
print("\nTop 3 values' locations:", locations)

    A   B   C   D
0  77  75  56  16
1  24  29  21  25
2  80  60  61  83
3  33  32  70  85

Top 3 values' locations: [(3, 'D'), (2, 'D'), (2, 'A')]

**37.** Given a DataFrame with a column of group IDs, 'grps', and a column of corresponding integer values, 'vals', replace any negative values in 'vals' with the group mean.

In [37]:
import pandas as pd
import numpy as np

# example
df = pd.DataFrame({
    'grps': list('aaabba'),
    'vals': [10, -3, 7, -2, 5, 9]
})

mean_a = df.loc[df['grps'] == 'a', 'vals'][df['vals'] >= 0].mean()
mean_b = df.loc[df['grps'] == 'b', 'vals'][df['vals'] >= 0].mean()

for i in range(len(df)):
    if df.loc[i, 'vals'] < 0:
        if df.loc[i, 'grps'] == 'a':
            df.loc[i, 'vals'] = mean_a
        elif df.loc[i, 'grps'] == 'b':
            df.loc[i, 'vals'] = mean_b

print(df)

  grps       vals
0    a  10.000000
1    a   8.666667
2    a   7.000000
3    b   5.000000
4    b   5.000000
5    a   9.000000

/tmp/ipython-input-3026516074.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '8.666666666666666' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[i, 'vals'] = mean_a

**38.** Implement a rolling mean over groups with window size 3, which ignores NaN value. For example consider the following DataFrame:

```python
>>> df = pd.DataFrame({'group': list('aabbabbbabab'),
                       'value': [1, 2, 3, np.nan, 2, 3,
                                 np.nan, 1, 7, 3, np.nan, 8]})
>>> df
   group  value
0      a    1.0
1      a    2.0
2      b    3.0
3      b    NaN
4      a    2.0
5      b    3.0
6      b    NaN
7      b    1.0
8      a    7.0
9      b    3.0
10     a    NaN
11     b    8.0
```
The goal is to compute the Series:

```
0     1.000000
1     1.500000
2     3.000000
3     3.000000
4     1.666667
5     3.000000
6     3.000000
7     2.000000
8     3.666667
9     2.000000
10    4.500000
11    4.000000
```
E.g. the first window of size three for group 'b' has values 3.0, NaN and 3.0 and occurs at row index 5. Instead of being NaN the value in the new column at this row index should be 3.0 (just the two non-NaN values are used to compute the mean (3+3)/2)

In [38]:
df = pd.DataFrame({'group': list('aabbabbbabab'),
                       'value': [1, 2, 3, np.nan, 2, 3,
                                 np.nan, 1, 7, 3, np.nan, 8]})

df['rolling_mean'] = (
    df.groupby('group')['value']
      .apply(lambda x: x.rolling(window=3, min_periods=1).mean())
      .reset_index(level=0, drop=True)
)

print(df)

   group  value  rolling_mean
0      a    1.0      1.000000
1      a    2.0      1.500000
2      b    3.0      3.000000
3      b    NaN      3.000000
4      a    2.0      1.666667
5      b    3.0      3.000000
6      b    NaN      3.000000
7      b    1.0      2.000000
8      a    7.0      3.666667
9      b    3.0      2.000000
10     a    NaN      4.500000
11     b    8.0      4.000000

## Series and DatetimeIndex

### Exercises for creating and manipulating Series with datetime data

Difficulty: *easy/medium*

pandas is fantastic for working with dates and times. These puzzles explore some of this functionality.

**39.** Create a DatetimeIndex that contains each business day of 2015 and use it to index a Series of random numbers. Let's call this Series `s`.

In [39]:
import pandas as pd
import numpy as np

dates = pd.bdate_range(start='2015-01-01', end='2015-12-31')
s = pd.Series(np.random.rand(len(dates)), index=dates)

print(s.head(10))

2015-01-01    0.716075
2015-01-02    0.287991
2015-01-05    0.383462
2015-01-06    0.749170
2015-01-07    0.878452
2015-01-08    0.102863
2015-01-09    0.092374
2015-01-12    0.354047
2015-01-13    0.551816
2015-01-14    0.033625
Freq: B, dtype: float64

**40.** Find the sum of the values in `s` for every Wednesday.

In [40]:
wednesdays = s[s.index.weekday == 2] # 2 is wednesday index if we start from monday
sum_wednesdays = wednesdays.sum()

print(sum_wednesdays)

26.703826642890036

**41.** For each calendar month in `s`, find the mean of values.

In [41]:
s_month_mean = s.resample('M').mean()
print(s_month_mean)

2015-01-31    0.411367
2015-02-28    0.479276
2015-03-31    0.560164
2015-04-30    0.575844
2015-05-31    0.535129
2015-06-30    0.439754
2015-07-31    0.509691
2015-08-31    0.556492
2015-09-30    0.511929
2015-10-31    0.508929
2015-11-30    0.412121
2015-12-31    0.476954
Freq: ME, dtype: float64

/tmp/ipython-input-3233910301.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  s_month_mean = s.resample('M').mean()

**42.** For each group of four consecutive calendar months in `s`, find the date on which the highest value occurred.

In [42]:
highest = s.groupby(pd.Grouper(freq='4M')).max()
print(highest)

2015-01-31    0.984042
2015-05-31    0.992396
2015-09-30    0.985032
2016-01-31    0.992430
Freq: 4ME, dtype: float64

/tmp/ipython-input-3692993255.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  highest = s.groupby(pd.Grouper(freq='4M')).max()

**43.** Create a DateTimeIndex consisting of the third Thursday in each month for the years 2015 and 2016.

In [43]:

dates = pd.date_range(
    start='2015-01-01',
    end='2016-12-31',
    freq='WOM-3THU'
)

print(dates)

DatetimeIndex(['2015-01-15', '2015-02-19', '2015-03-19', '2015-04-16',
               '2015-05-21', '2015-06-18', '2015-07-16', '2015-08-20',
               '2015-09-17', '2015-10-15', '2015-11-19', '2015-12-17',
               '2016-01-21', '2016-02-18', '2016-03-17', '2016-04-21',
               '2016-05-19', '2016-06-16', '2016-07-21', '2016-08-18',
               '2016-09-15', '2016-10-20', '2016-11-17', '2016-12-15'],
              dtype='datetime64[ns]', freq='WOM-3THU')

## Cleaning Data

### Making a DataFrame easier to work with

Difficulty: *easy/medium*

It happens all the time: someone gives you data containing malformed strings, Python, lists and missing data. How do you tidy it up so you can get on with the analysis?

Take this monstrosity as the DataFrame to use in the following puzzles:

```python
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})
```
(It's some flight data I made up; it's not meant to be accurate in any way.)

**44.** Some values in the the FlightNumber column are missing. These numbers are meant to increase by 10 with each row so 10055 and 10075 need to be put in place. Fill in these missing numbers and make the column an integer column (instead of a float column).

In [44]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})

# interpolate function fill data frame on basic of smart pattern
df['FlightNumber'] = df['FlightNumber'].interpolate().astype(int)

df

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris         10045      [23, 47]               KLM(!)
1      MAdrid_miLAN         10055            []    <Air France> (12)
2  londON_StockhOlm         10065  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis         10075          [13]       12. Air France
4   Brussels_londOn         10085      [67, 32]          "Swiss Air"

**45.** The From\_To column would be better as two separate columns! Split each string on the underscore delimiter `_` to give a new temporary DataFrame with the correct values. Assign the correct column names to this temporary DataFrame.

In [45]:
temp = df['From_To'].str.split('_', expand=True)
temp.columns = ['From', 'To']

temp

       From         To
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn

**46.** Notice how the capitalisation of the city names is all mixed up in this temporary DataFrame. Standardise the strings so that only the first letter is uppercase (e.g. "londON" should become "London".)

In [46]:
temp['From'] = temp['From'].str.capitalize()
temp['To'] = temp['To'].str.capitalize()

temp

       From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London

**47.** Delete the From_To column from `df` and attach the temporary DataFrame from the previous questions.

In [47]:
df = df.drop('From_To', axis=1)
df = pd.concat([df, temp], axis=1)

df

   FlightNumber  RecentDelays              Airline      From         To
0         10045      [23, 47]               KLM(!)    London      Paris
1         10055            []    <Air France> (12)    Madrid      Milan
2         10065  [24, 43, 87]  (British Airways. )    London  Stockholm
3         10075          [13]       12. Air France  Budapest      Paris
4         10085      [67, 32]          "Swiss Air"  Brussels     London

**48**. In the Airline column, you can see some extra puctuation and symbols have appeared around the airline names. Pull out just the airline name. E.g. `'(British Airways. )'` should become `'British Airways'`.

In [48]:
df['Airline'] = df['Airline'].str.replace('[^a-zA-Z\s]', '', regex=True).str.strip()
df

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-2890539967.py:1: SyntaxWarning: invalid escape sequence '\s'
  df['Airline'] = df['Airline'].str.replace('[^a-zA-Z\s]', '', regex=True).str.strip()

   FlightNumber  RecentDelays          Airline      From         To
0         10045      [23, 47]              KLM    London      Paris
1         10055            []       Air France    Madrid      Milan
2         10065  [24, 43, 87]  British Airways    London  Stockholm
3         10075          [13]       Air France  Budapest      Paris
4         10085      [67, 32]        Swiss Air  Brussels     London

**49**. In the RecentDelays column, the values have been entered into the DataFrame as a list. We would like each first value in its own column, each second value in its own column, and so on. If there isn't an Nth value, the value should be NaN.

Expand the Series of lists into a DataFrame named `delays`, rename the columns `delay_1`, `delay_2`, etc. and replace the unwanted RecentDelays column in `df` with `delays`.

In [49]:

delays = pd.DataFrame(df['RecentDelays'].to_list())
delays.columns = [f'delay_{i+1}' for i in range(delays.shape[1])]
df = df.drop('RecentDelays', axis=1).join(delays)

df

,FlightNumber,Airline,From,To,delay_1,delay_2,delay_3
0,10045,KLM,London,Paris,23.0,47.0,NaN
1,10055,Air France,Madrid,Milan,NaN,NaN,NaN
2,10065,British Airways,London,Stockholm,24.0,43.0,87.0
3,10075,Air France,Budapest,Paris,13.0,NaN,NaN
4,10085,Swiss Air,Brussels,London,67.0,32.0,NaN

The DataFrame should look much better now.

## Using MultiIndexes

### Go beyond flat DataFrames with additional index levels

Difficulty: *medium*

Previous exercises have seen us analysing data from DataFrames equipped with a single index level. However, pandas also gives you the possibilty of indexing your data using *multiple* levels. This is very much like adding new dimensions to a Series or a DataFrame. For example, a Series is 1D, but by using a MultiIndex with 2 levels we gain of much the same functionality as a 2D DataFrame.

The set of puzzles below explores how you might use multiple index levels to enhance data analysis.

To warm up, we'll look make a Series with two index levels.

**50**. Given the lists `letters = ['A', 'B', 'C']` and `numbers = list(range(10))`, construct a MultiIndex object from the product of the two lists. Use it to index a Series of random numbers. Call this Series `s`.

In [50]:
import pandas as pd
import numpy as np

letters = ['A', 'B', 'C']
numbers = list(range(10))

index = pd.MultiIndex.from_product([letters, numbers], names=['Letter', 'Number'])

s = pd.Series(np.random.randn(len(index)), index=index)

s.head(12)

Letter  Number
A       0         0.487074
        1         0.144842
        2        -0.085610
        3         0.710540
        4         0.930960
        5         0.875074
        6        -0.711565
        7        -0.361209
        8        -2.109247
        9        -1.093768
B       0         1.204506
        1         0.111081
dtype: float64

**51.** Check the index of `s` is lexicographically sorted (this is a necessary proprty for indexing to work correctly with a MultiIndex).

In [51]:
s.index.is_monotonic_increasing

True

# **52**. Select the labels `1`, `3` and `6` from the second level of the MultiIndexed Series.

In [52]:
out = s.loc[(slice(None), [1, 3, 6])]
out

Letter  Number
A       1         0.144842
        3         0.710540
        6        -0.711565
B       1         0.111081
        3         0.394598
        6        -0.153023
C       1         0.190564
        3         0.047512
        6        -0.170753
dtype: float64

**53**. Slice the Series `s`; slice up to label 'B' for the first level and from label 5 onwards for the second level.

In [53]:
sliced = s.loc[pd.IndexSlice[:'B', 5:]]
sliced

Letter  Number
A       5         0.875074
        6        -0.711565
        7        -0.361209
        8        -2.109247
        9        -1.093768
B       5         0.224904
        6        -0.153023
        7        -0.240730
        8         0.081583
        9         1.238170
dtype: float64

**54**. Sum the values in `s` for each label in the first level (you should have Series giving you a total for labels A, B and C).

In [54]:
s_sum_alt = s.groupby(level='Number').sum()
s_sum_alt

Number
0    3.875358
1    0.446486
2    1.377221
3    1.152651
4    1.552160
5    1.528199
6   -1.035342
7   -2.956716
8   -2.495471
9    0.015000
dtype: float64

**55**. Suppose that `sum()` (and other methods) did not accept a `level` keyword argument. How else could you perform the equivalent of `s.sum(level=1)`?

In [55]:
s_sum_alt = s.groupby(level='Number').sum()
s_sum_alt

Number
0    3.875358
1    0.446486
2    1.377221
3    1.152651
4    1.552160
5    1.528199
6   -1.035342
7   -2.956716
8   -2.495471
9    0.015000
dtype: float64

**56**. Exchange the levels of the MultiIndex so we have an index of the form (letters, numbers). Is this new Series properly lexsorted? If not, sort it.

In [56]:
s_swapped = s.swaplevel()
s_swapped.head()

Number  Letter
0       A         0.487074
1       A         0.144842
2       A        -0.085610
3       A         0.710540
4       A         0.930960
dtype: float64